[[redirects]]
  from = "/"
  to = "http://khyateh.com"
  status = 301
  force = false
[build]
  publish = "public"
  command = "yarn build"
[build.environment]
  YARN_VERSION = "1.7.0"
  YARN_FLAGS = "--no-ignore-optional"
